### ISSUE TITLE
Covariance and contravariant

### ISSUE THREAD

**Issue by HaritzPuerto** [FelipeSulser/Scala_DataStructures#1]
You already know smthg about this, don't you?
I'm reading Scala By Example document. This is explained at page 63 but I don't understand what a contravariant poisition is.

```
class Stack[+A] {
    def push(x: A): Stack[A] =
               ^ covariant type parameter A
               appears in contravariant position.
```
'cuz of that, Scala compiler rejects that line.

Thnx

**Comment by FelipeSulser** [comment]
Unfortunately it has nothing to do with vector or tensors :( 
(as far as i know)

In scala a covariant type parameter is allowed to vary down as the class is subtyped  
e.g.

trait List[+A]

List[Int] is a subtype of List[AnyVal] therefore it "fits"


and contravariance is exactly the opposite, parameters vary upward with subtyping

**Comment by HaritzPuerto** [comment]
I've re-read the example and now I understand what the problem is. Thnx!
