### ISSUE TITLE
Maxiphobic heaps

### ISSUE THREAD

**Issue by HaritzPuerto** [FelipeSulser/Scala_DataStructures#2]
@FelipeSulser 
I think I know what the problem is.
First, you want to use pattern matching but you are not saying 'match' so the compiler doesn't know to what thing you want to apply pattern matching. 
Here you have the correction:
```
 def weight(a : Node[Int]): Int = a match {
      case null => 0
      case a => a.data + weight(a.right) + weight(a.left)
    }
```
In addition, I think you should define a "null" class, like finalNode or smthg similar. And, I think case a will never work, I think you should write the name of the class, but that doesn't work for me...

**Comment by FelipeSulser** [comment]
Oh i see!
Anyways for some reason even tho i specify the return value is Int it says that for:
`
case null => 0
      case a => a.data + weight(a.right) + weight(a.left)
`
0 and weight(a.right) are supposed to be strings
?? :(
